# Generated by Django 3.2.6 on 2021-08-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=36, verbose_name='Логин покупателя')),
                ('item', models.CharField(max_length=36, verbose_name='Наименование товара')),
                ('total', models.FloatField(verbose_name='Сумма сделки')),
                ('quantity', models.IntegerField(verbose_name='Количество товара, шт.')),
                ('date', models.DateTimeField(verbose_name='Дата и время регистрации сделки')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Список продуктов',
                'ordering': ('-date',),
            },
        ),
    ]
